server:
  port: 8001
spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/test_delete?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: tiger!


eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true。
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      #单机版
#      defaultZone: http://localhost:7001/eureka
      # 集群版
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: payment8001
    #访问路径可以显示IP地址
    prefer-ip-address: true
    #Eureka客户端向服务端发送心跳的时间间隔，单位为秒(默认是30秒)
    #lease-renewal-interval-in-seconds: 1
    #Eureka服务端在收到最后一次心跳后等待时间上限，单位为秒(默认是90秒)，超时将剔除服务
    #lease-expiration-duration-in-seconds: 2

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.atguigu.common.entitys    # 所有Entity别名类所在包
logging:
  level:
    com.atguigu.payment.dao: DEBUG

# 健康检查 通过下面的配置启用所有的监控端点，默认情况下，这些端点是禁用的
# “*”号代表启用所有的监控端点，可以单独启用，例如，health，info，metrics等
management:
  endpoints:
    web:
      exposure:
        include: "*"
  server:
    port: ${server.port}
    servlet:
      context-path: /
    ssl:
      enabled: false
  endpoint:
    health:
      show-details: always